# Prometheus configuration for Healthcare SaaS monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'healthcare-saas'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Healthcare SaaS API metrics
  - job_name: 'healthcare-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:3001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'healthcare-api'

  # Healthcare SaaS Frontend metrics
  - job_name: 'healthcare-frontend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['frontend:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'healthcare-frontend'

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['172.20.0.1:9323']

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://healthcare-saas.jp
          - https://healthcare-saas.jp/api/health
          - https://api.healthcare-saas.jp/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL certificate monitoring
  - job_name: 'ssl'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://healthcare-saas.jp
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ssl-exporter:9219